CREATE DATEBASE adminho;

CREATE TABLE TipoDocumento
( id INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
codigo VARCHAR(30) NOT NULL,
descripcion VARCHAR(30) NOT NULL);

CREATE TABLE persona
( id INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
 id_tipdoc INT (3) NOT NULL,
 num_doc INT(10) NOT NULL,
 nombre VARCHAR(50) NOT NULL,
 apellido VARCHAR (50) NOT NULL,
 celular INT(10) NOT NULL,
 email VARCHAR(50) NOT NULL);
 